// Generated by https://quicktype.io

export interface Resumen {
  cantidadCorrectas: number;
  idCuestionario: string;
  puntosTotales: number;
  cantidadPreguntas: number;
  nombreParticipante: string;
  fecha: string;
  cantidadIncorrectas: number;
  listRespuestasUsuario: ListRespuestasUsuario[];
}

export interface ListRespuestasUsuario {
  indexRespuestaSeleccionada: number;
  segundos: number;
  listRespuestas: ListRespuesta[];
  titulo: string;
  puntosObtenidos: number;
}

export interface ListRespuesta {
  descripcion: string;
  esCorrecta: boolean;
}
